export const EXCEPTION = {
  EXIST_PROMOTION_CODE: "PROMOTION CODE ALREADY EXIST",
  OVER_DISCOUNT_PERCENTAGE: "OVER RATE PERCENTAGE",
  LOCATION_ALREADY_EXIST : "Location is already exist",
  NOT_FOUND: "NOT FOUND"
};

export const USER_EXCEPTION = {
  USER_NOT_FOUND: "USER NOT FOUND",
  INCORRECT_PASSWORD: "INCORRECT PASSWORD",
  USER_EXIST: "USER ALREADY EXIST",
  USER_NOT_ACTIVE: "USER IS NOT ACTIVE",
  CURREND_NAME_PASSWORD: "Wrong Employee id and Password"
};
export const COMPANY_EXCEPTION = {
  NOT_FOUND: "COMPANY NOT FOUND",
};
export const USER_POSITION = {
  SALE: "Sale",
  AGENCY: "AGENCY",
  BRANCH: "BRANCH",
};

export const STATUS = {
  ACTIVE: "ACTIVE",
  DISABLE: "INACTIVE",
};

export const DRIVER_EXCEPTION = {
  DRIVER_NOT_FOUND: "DRIVER NOT FOUND",
  DRIVER_EXIST: "DRIVER_ALREADY EXIST",
};

export const VEHICLE_EXCEPTION = {
  VEHICLE_NOT_FOUND: "VEHICLE NOT FOUND",
  VEHICLE_EXIST: "VEHICLE ALREADY EXIST",
};
