const swaggerAutogen = require("swagger-autogen")();
require("dotenv").config();

// import swaggerAutogen from 'swagger-autogen';

const doc = {
  info: {
    version: "1.0.0",
    title: "HRMS ADMIN API",
    description: "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: process.env.HOST_SWAGGER,
  basePath: "/",
  schemes: process.env.SCHEMES,
  consumes: ["application/json"],
  produces: ["application/json"],
  tags: [
    {
      name: "Authentication",
    },
  ],
  securityDefinitions: {
    bearerAuth: {
      name: "Authorization",
      in: "header",
      type: "apiKey",
    },
  },
  definitions: {
    Response: {
      status: "true/false",
      "data?": "[],{}",
      "error?": "is optional",
      "error_description?": "exception detail",
    },
    DateFormat: "2022-10-10",

    "Licenses/Identifer": {
      front: "base64/img",
      back: "base64/img",
    },
    SHIFT: "ALL/DAY/NIGHT",
  },
};

const outputFile = "./swagger_output.json";
const endpointsFiles = ["./src/index.js"];

swaggerAutogen(outputFile, endpointsFiles, doc);
//     .then(() => {
//     require("./index")    // Your project's root file
// })
